/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObservacionesRouteImport } from './routes/observaciones'
import { Route as IndexRouteImport } from './routes/index'

const ObservacionesRoute = ObservacionesRouteImport.update({
  id: '/observaciones',
  path: '/observaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/observaciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/observaciones'
  id: '__root__' | '/' | '/observaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObservacionesRoute: typeof ObservacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/observaciones': {
      id: '/observaciones'
      path: '/observaciones'
      fullPath: '/observaciones'
      preLoaderRoute: typeof ObservacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObservacionesRoute: ObservacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
