/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObservacionesRouteImport } from './routes/observaciones'
import { Route as InstruccionesRouteImport } from './routes/instrucciones'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ObservacionesRoute = ObservacionesRouteImport.update({
  id: '/observaciones',
  path: '/observaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InstruccionesRoute = InstruccionesRouteImport.update({
  id: '/instrucciones',
  path: '/instrucciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ajustes': typeof AjustesRoute
  '/instrucciones': typeof InstruccionesRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ajustes': typeof AjustesRoute
  '/instrucciones': typeof InstruccionesRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ajustes': typeof AjustesRoute
  '/instrucciones': typeof InstruccionesRoute
  '/observaciones': typeof ObservacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/ajustes' | '/instrucciones' | '/observaciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/ajustes' | '/instrucciones' | '/observaciones'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ajustes'
    | '/instrucciones'
    | '/observaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AjustesRoute: typeof AjustesRoute
  InstruccionesRoute: typeof InstruccionesRoute
  ObservacionesRoute: typeof ObservacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/observaciones': {
      id: '/observaciones'
      path: '/observaciones'
      fullPath: '/observaciones'
      preLoaderRoute: typeof ObservacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrucciones': {
      id: '/instrucciones'
      path: '/instrucciones'
      fullPath: '/instrucciones'
      preLoaderRoute: typeof InstruccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AjustesRoute: AjustesRoute,
  InstruccionesRoute: InstruccionesRoute,
  ObservacionesRoute: ObservacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
